version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
      LANG: ru_RU.UTF-8

    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker"]
      interval: 5s
      retries: 5

  app:
    build: ./app
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
      POSTGRES_HOST: db
    tty: true
    stdin_open: true
